fix(pm/collabora-gtimelog): revert to 25.05
There are some libraries that were updated in nixpkgs 25.11 but which
Collabora gtimelog doesn't support newer versions of. Building gtimelog
from 25.11 will get you an error that looks like this

    Traceback (most recent call last):
      File "/nix/store/akvr4z3wjiw2gizz6jnbb3f29wa29h8a-python3.13-pygobject-3.54.5/lib/python3.13/site-packages/gi/importer.py", line 137, in create_module
        introspection_module = get_introspection_module(namespace)
      File "/nix/store/akvr4z3wjiw2gizz6jnbb3f29wa29h8a-python3.13-pygobject-3.54.5/lib/python3.13/site-packages/gi/module.py", line 244, in get_introspection_module
        module = IntrospectionModule(namespace, version)
      File "/nix/store/akvr4z3wjiw2gizz6jnbb3f29wa29h8a-python3.13-pygobject-3.54.5/lib/python3.13/site-packages/gi/module.py", line 104, in __init__
        repository.require(namespace, version)
        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
    gi.RepositoryError: Typelib file for namespace 'cairo', version '1.0' not found

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/nix/store/bmy9cw4hbnrq00cc29sza5083yamw74s-gtimelog-0.12.0/bin/.gtimelog-wrapped", line 6, in <module>
        from gtimelog.main import main
      File "/nix/store/bmy9cw4hbnrq00cc29sza5083yamw74s-gtimelog-0.12.0/lib/python3.13/site-packages/gtimelog/main.py", line 72, in <module>
        from gi.repository import Gdk, Gio, GLib, GObject, Gtk, Pango, Soup  # noqa: E402
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/nix/store/akvr4z3wjiw2gizz6jnbb3f29wa29h8a-python3.13-pygobject-3.54.5/lib/python3.13/site-packages/gi/importer.py", line 139, in create_module
        raise ImportError(e) from e
    ImportError: Typelib file for namespace 'cairo', version '1.0' not found

From using nix-locate we can see that cairo-1.0.typelib is in gobject
introspection 1.84.0...

    $ nix-locate cairo-1.0.typelib
    gobject-introspection.out                             0 s /nix/store/i6asc7b7ws92inj5bqvmdbcs3n77dknz-gobject-introspection-wrapped-1.84.0/lib/girepository-1.0/cairo-1.0.typelib
    gobject-introspection-unwrapped.out              14,740 r /nix/store/dpwppqwbm76q7h1gk8mv0mg4ylf4b551-gobject-introspection-1.84.0/lib/girepository-1.0/cairo-1.0.typelib

...but search.nixos.org tells us that gobject-introspection is at 1.86.0

Downgrading to 25.05 fixes this issue...